# Tokyo Night tokyonight-storm theme for Kitty

# Basic colors
foreground              #c0caf5
background              #24283b
selection_foreground    #24283b
selection_background    #7aa2f7

# Cursor colors
cursor                  #c0caf5
cursor_text_color       #24283b

# URL underline color
url_color               #7dcfff

# Window border colors
active_border_color     #7aa2f7
inactive_border_color   tokyonight-storm1
bell_border_color       #f7768e

# Tab bar colors
active_tab_foreground   #24283b
active_tab_background   #7aa2f7
inactive_tab_foreground #c0caf5
inactive_tab_background tokyonight-storm1
tab_bar_background      tokyonight-storm2

# Colors for marks
mark1_foreground        #24283b
mark1_background        #7aa2f7
mark2_foreground        #24283b
mark2_background        #bb9af7
mark3_foreground        #24283b
mark3_background        #9ece6a

# Black
color0                  tokyonight-storm3
color8                  tokyonight-storm4

# Red
color1                  #f7768e
color9                  #f7768e

# Green
color2                  #9ece6a
color10                 #9ece6a

# Yellow
color3                  #e0af68
color11                 #e0af68

# Blue
color4                  #7aa2f7
color12                 #7aa2f7

# Magenta
color5                  #bb9af7
color13                 #bb9af7

# Cyan
color6                  #7dcfff
color14                 #7dcfff

# White
color7                  tokyonight-storm0
color15                 tokyonight-storm0
