# Tokyo Night tokyonight-day theme for Kitty

# Basic colors
foreground              #3760bf
background              #e6e7ed
selection_foreground    #e6e7ed
selection_background    #3760bf

# Cursor colors
cursor                  #3760bf
cursor_text_color       #e6e7ed

# URL underline color
url_color               #2ac3de

# Window border colors
active_border_color     #3760bf
inactive_border_color   tokyonight-day1
bell_border_color       #d95763

# Tab bar colors
active_tab_foreground   #e6e7ed
active_tab_background   #3760bf
inactive_tab_foreground #3760bf
inactive_tab_background tokyonight-day1
tab_bar_background      tokyonight-day2

# Colors for marks
mark1_foreground        #e6e7ed
mark1_background        #3760bf
mark2_foreground        #e6e7ed
mark2_background        #5b4aff
mark3_foreground        #e6e7ed
mark3_background        #25a45c

# Black
color0                  tokyonight-day3
color8                  tokyonight-day4

# Red
color1                  #d95763
color9                  #d95763

# Green
color2                  #25a45c
color10                 #25a45c

# Yellow
color3                  #a482d4
color11                 #a482d4

# Blue
color4                  #3760bf
color12                 #3760bf

# Magenta
color5                  #5b4aff
color13                 #5b4aff

# Cyan
color6                  #2ac3de
color14                 #2ac3de

# White
color7                  tokyonight-day0
color15                 tokyonight-day0
