## 1. BUILD ARGS
# These allow changing the produced image by passing different build args to adjust
# the source from which your image is built.
# Build args can be provided on the commandline when building locally with:
#   podman build -f Containerfile --build-arg FEDORA_VERSION=40 -t local-image

ARG BASE_IMAGE_NAME="silverblue"
ARG BASE_IMAGE_VERSION="43"
ARG SOURCE_SUFFIX="-main"
ARG SOURCE_IMAGE="${BASE_IMAGE_NAME}${SOURCE_SUFFIX}"
ARG BASE_IMAGE="ghcr.io/ublue-os/${SOURCE_IMAGE}"

## SOURCE_TAG arg must be a version built for the specific image: eg, 39, 40, gts, latest
ARG SOURCE_TAG="latest"

## Build Alacritty
#FROM fedora as BUILDER
#WORKDIR /tmp
#
#RUN dnf install -y git cmake freetype-devel fontconfig-devel libxcb-devel libxkbcommon-devel g++
#
#RUN curl -sSf https://sh.rustup.rs | sh -s -- -y -v &&\
#  . "$HOME/.cargo/env" &&\
#  rustup override set stable &&\
#  rustup update stable &&\
#  curl -OL "https://github.com/alacritty/alacritty/archive/refs/tags/v${ALACRITTY_VERSION}.tar.gz" &&\
#  ls -lah &&\
#  tar zxvf "v${ALACRITTY_VERSION}.tar.gz && cd alacritty-${ALACRITTY_VERSION}" &&\
#  cargo build --release --no-default-features --features=wayland


FROM ${BASE_IMAGE}:${BASE_IMAGE_VERSION}

### 3. MODIFICATIONS
## make modifications desired in your image and install packages by modifying the build.sh script
## the following RUN directive does all the things required to run "build.sh" as recommended.

# Distrobox default config
COPY os/butler.sh /usr/bin/butler
COPY os/config/distrobox.conf /etc/distrobox/distrobox.conf

# TODO make the /usr/share/apparatus folder a variable
# Alacritty
#COPY os/config/alacritty/* /usr/share/apparatus/alacritty/

# Build script
COPY os/build.sh /tmp/build.sh

## Alacritty files
#COPY --from=BUILDER /tmp/alacritty-${ALACRITTY_VERSION}/target/release/alacritty /usr/bin/alacritty
#COPY --from=BUILDER /tmp/alacritty-${ALACRITTY_VERSION}/extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
#COPY --from=BUILDER /tmp/alacritty-${ALACRITTY_VERSION}/extra/linux/Alacritty.desktop /tmp/Alacritty.desktop

# Apparatus
#COPY os/config/apparatus/Apparatus.desktop /tmp/Apparatus.desktop

RUN --mount=type=cache,dst=/var/cache/libdnf5 \
    --mount=type=cache,dst=/var/cache/rpm-ostree \
    --mount=type=bind,from=goal,source=/,target=/goal \
    /ctx/build.sh


RUN mkdir -p /var/lib/alternatives && \
    /tmp/build.sh && \
    ostree container commit

## NOTES:
# - /var/lib/alternatives is required to prevent failure with some RPM installs
# - All RUN commands must end with ostree container commit
#   see: https://coreos.github.io/rpm-ostree/container/#using-ostree-container-commit
