## 1. BUILD ARGS
# These allow changing the produced image by passing different build args to adjust
# the source from which your image is built.
# Build args can be provided on the commandline when building locally with:
#   podman build -f Containerfile --build-arg FEDORA_VERSION=40 -t local-image

ARG BASE_IMAGE_NAME="silverblue"
ARG BASE_IMAGE_VERSION="43"
ARG SOURCE_SUFFIX="-main"
ARG SOURCE_IMAGE="${BASE_IMAGE_NAME}${SOURCE_SUFFIX}"
ARG BASE_IMAGE="ghcr.io/ublue-os/${SOURCE_IMAGE}"

# == DELIVERY image (contains scripts and files)
# Content copied into this image is later mounted and can be used to build the image
FROM ${BASE_IMAGE}:${BASE_IMAGE_VERSION} as delivery
COPY /os/build_files /build_files

# == IMAGE
FROM ${BASE_IMAGE}:${BASE_IMAGE_VERSION}


# Distrobox default config
#COPY os/butler.sh /usr/bin/butler
#COPY os/config/distrobox.conf /etc/distrobox/distrobox.conf

# TODO make the /usr/share/apparatus folder a variable
# Alacritty
#COPY os/config/alacritty/* /usr/share/apparatus/alacritty/

# Build script
#COPY os/build.sh /tmp/build.sh

## Alacritty files
#COPY --from=BUILDER /tmp/alacritty-${ALACRITTY_VERSION}/target/release/alacritty /usr/bin/alacritty
#COPY --from=BUILDER /tmp/alacritty-${ALACRITTY_VERSION}/extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
#COPY --from=BUILDER /tmp/alacritty-${ALACRITTY_VERSION}/extra/linux/Alacritty.desktop /tmp/Alacritty.desktop

# Apparatus
#COPY os/config/apparatus/Apparatus.desktop /tmp/Apparatus.desktop

RUN --mount=type=cache,dst=/var/cache/libdnf5 \
    --mount=type=cache,dst=/var/cache/rpm-ostree \
    --mount=type=bind,from=delivery,source=/,target=/delivery \
    /delivery/build_files/build.sh


RUN mkdir -p /var/lib/alternatives && \
    #/tmp/build.sh && \
    ostree container commit

## NOTES:
# - /var/lib/alternatives is required to prevent failure with some RPM installs
# - All RUN commands must end with ostree container commit
#   see: https://coreos.github.io/rpm-ostree/container/#using-ostree-container-commit
